name: 'Plant UML Github Action'
description: 'Generates PlantUML diagrams'
inputs:
  plantuml-args:
    description: 'PlantUML command arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.plantuml-args }}
